name: CI-CD

on:
  push:
    branches: ["master"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v5.0.0
        with:
          file: ./dockerfile
          push: true
          tags: |
            pedropinguelli/py:3.0
            
    
