name: CI-CD

on:
  push:
    branches: ["master"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Autenticando no dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PWD}}
          
      - name: realizando o push
        uses: docker/build-push-action@v5.0.0
        with:
          file: ./dockerfile
          push: true
          tags: |
            pedropinguelli/py:3.0
            
    
